services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:latest # <<< Desired release version here (or use beta to get the latest beta version)
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - /data/music-assistant-server/data:/data/
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info
    labels:
      - "traefik.backend=music-assistant-server"
      - "traefik.docker.network=host"
      - "traefik.http.routers.music-assistant-server.rule=Host(`mass.home`)"
      - "traefik.frontend.rule=Host:mass.home"
      - "traefik.http.routers.music-assistant-server.entrypoints=web"
      - "traefik.enable=true"
      - "traefik.port=8095"
      - "traefik.default.protocol=8095"
      - "traefik.http.services.music-assistant-server.loadbalancer.server.port=8095"